// J4 Legacy Properties — shared head behavior (analytics)
// Loaded as a defer script on every page.
//
// ONE copy of the GA4 tag for the whole site. Deliberately not pasted into each
// of the 118 pages: J4FS previously carried its GA4 block on all 18 of its pages
// wrapped in an HTML comment, so it never fired once and nothing reported it.
// One file means one place to be wrong, and changing the ID is a one-line edit.
//
// NOTE: the /properties/ pages are GENERATED by build-properties.js. The
// <script defer src="/site-head.js"> line lives in that script's <head>
// template too, so regenerated pages keep the tag. If you add a new page
// template anywhere, add the tag there or that page ships unmeasured.
//
// window.gtag is exposed globally so forms.js can fire conversion events later.
// No conversion events are wired yet — that is a separate decision.

(function () {
  // ── Google Analytics 4 — J4 Legacy Properties property (552122505) ──
  var GA4_ID = 'G-HKGXS4B10C';
  var ga = document.createElement('script');
  ga.async = true;
  ga.src = 'https://www.googletagmanager.com/gtag/js?id=' + GA4_ID;
  document.head.appendChild(ga);
  window.dataLayer = window.dataLayer || [];
  function gtag() { window.dataLayer.push(arguments); }
  window.gtag = gtag;
  gtag('js', new Date());
  gtag('config', GA4_ID);
})();
